version: "3"

services:
  mysql:
    network_mode: host
    container_name: dbforbot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50770:3306"
   # restart: always

  application:
    network_mode: host
    container_name: appbot
    build:
      context: .
      dockerfile: DockerfileAPP
    restart: on-failure

